import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/widget/Navbar";
import Footer from "@/components/widget/Footer";
import Logo from "./Logo.png";
import { Bricolage_Grotesque } from "next/font/google";
import { Import } from "lucide-react";

type NavLink = {
  label: string;
  href: string;
  ariaLabel: string;  // Remove optional modifier
};

type NavItem = {
  label: string;
  bgColor: string;
  textColor: string;
  links: NavLink[];
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kazeworks | Riovaldo Alfiyan Fahmi Rahman Portfolio",
  description: "Generated by create next app",
};

const navItems: NavItem[] = [
  {
    label: "About",
    bgColor: "#0D0716",
    textColor: "#fff",
    links: [
      { label: "MBGo", href: "/about/MBGo", ariaLabel: "About Company" },
      { label: "Fitur", href: "/about/fitur", ariaLabel: "About Features  " },
    ],
  } as const,
  {
    label: "Projects",
    bgColor: "#170D27",
    textColor: "#fff",
    links: [
      { label: "Featured", href: "/projects/featured", ariaLabel: "Featured Projects" },
      { label: "Case Studies", href: "/projects/case-studies", ariaLabel: "Project Case Studies" },
    ],
  } as const,
  {
    label: "Contact",
    bgColor: "#271E37",
    textColor: "#fff",
    links: [
      { label: "Email", href: "/contact/email", ariaLabel: "Email us" },
      { label: "Twitter", href: "/contact/twitter", ariaLabel: "Twitter" },
      { label: "LinkedIn", href: "/contact/linkedin", ariaLabel: "LinkedIn" },
    ],
  } as const,
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bricolage.variable} antialiased`}
        style={{ fontFamily: "var(--font-bricolage), var(--font-geist-sans), system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial" }}
      >
        <Navbar
          logo={Logo}
          logoAlt="Kazera Logo"
          items={navItems}
          baseColor="#fff"
          menuColor="#000"
          ease="power3.out"
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
